### ISSUE TITLE
Support DirectX device selection

### ISSUE THREAD

**Issue by itsmattkc** [itsmattkc/LEGOIslandRebuilder#16]
This is the last bit that Rebuilder can't do that CONFIG.EXE can. Unfortunately it's a little tough since it requires interfacing with a machine language DLL through C#, but this definitely isn't impossible.

**Comment by Halamix2** [comment]
Example from my code for other game using DirectX for Managed Code
Reference to Micorsoft.DirectX needs to be added; dll is localized at `C:\Windows\Microsoft.NET\DirectX for Managed Code\1.0.2902.0\Microsoft.DirectX.dll`
IIRC there was a bug in VS check for the LoaderLock exception; it needs to be turned off, otherwise this will crash.
```csharp
using Microsoft.DirectX;
using Microsoft.DirectX.DirectDraw;

DevicesCollection ddDevices = new DevicesCollection(GetDevicesFlags.NonDisplayDevices);// GetDevicesFlags.AttachedSecondaryDevice);
foreach (DeviceInformation d in ddDevices)
{
	videoD3DDriver.Items.Add(d.Description);
}
videoD3DDriver.SelectedIndex = 0;

// idea: GetDevicesFlags.AttachedSecondaryDevice - read if there is any radeon and if yes enable fix by default?
DevicesCollection ddDevicesRadeon = new DevicesCollection(GetDevicesFlags.AttachedSecondaryDevice);
foreach (DeviceInformation d in ddDevicesRadeon)
{
	Debug.WriteLine(d.Driver);
	Debug.WriteLine(d.Description);
	Debug.WriteLine(d.Name);
}
```

sources for that bug:
https://stackoverflow.com/questions/2567543/loaderlock-was-detected-and-turning-off-the-warning-does-not-work
https://stackoverflow.com/questions/56642/loader-lock-error
