### ISSUE TITLE
Consider port to C++

### ISSUE THREAD

**Issue by itsmattkc** [itsmattkc/LEGOIslandRebuilder#18]
Rebuilder was originally written in C# for simplicity and ease of deployment, however relying on .NET does have one major drawback: no Windows 95/NT support.

One of Rebuilder's goals is that it will work on old PCs just as well as new PCs, however that goal is somewhat crippled by relying on .NET and means Rebuilder will never run on the operating system that LEGO Island was actually intended to run on.

I am personally in favor of this in the interests of continuing to improve Rebuilder and don't even think it will take that long. I'm more comfortable with C++ anyway and using it will also help us take over more functionality from LEGO Island such as #16. I'm looking at MFC as a helper library to use instead of just the Win32 API.

Of course I'm opening to other opinions on this topic if anyone has any.

**Comment by quorten** [comment]
Sure, I agree.  I'd probably be better as it would allow common functions between tools and the game engine rewrite to come from the same code library.

**Comment by Halamix2** [comment]
Building C++ VS project for Win 95 would require downgrading to Visual Studio 2005 or 2003 (2005 requires some more work, like manual checking if a API call was implemented in Win 95).
I wasn't able to find info about 95 support in MinGW, all I found is that [WINVER and friends](https://devblogs.microsoft.com/oldnewthing/20070411-00/?p=27283) needs to be set

**Comment by quorten** [comment]
@Halamix2 MinGW generally does not require setting any Windows version flags unless you're using certain newer areas of the API, version 3.4.4 works best for Windows 9x.  (Never MinGW versions dropped support to self-host compiles on Windows 9x but they can still cross-compile.)  Likewise for Visual Studio 2005, I'd recommend MSVC6 at newest.  The main reason to stay away from using the newer compilers is the larger standard C libraries that need to be statically linked, MSVC7+ in particular doesn't use `msvcrt.dll`.

But, good point, for the uninitiated, it might be more difficult to compile without very detailed instructions, which in itself is difficult to follow correctly.  Personally I'm not familiar with what kinds of vintage Windows knowledge newer community members may lack because I did Windows development back during its heyday.
