### ISSUE TITLE
Lego island isn't booting when using rebuilder but works fine by itself

### ISSUE THREAD

**Issue by mjcox244** [itsmattkc/LEGOIslandRebuilder#21]
This might be a simple fix but ill explain how i have set it up
I have an iso mounted as my E drive that has all the game data on it
I have installed lego island via the installer that came on the disk
i have d3drm in my program files folder for lego island
i can boot lego island fine and even edit the config

BUT as soon as i try rebuilder i get the error 
"Lego Island" failed to start please quit all other apps and try again

**Comment by mjcox244** [comment]
Fixed the error of it not starting.
had to change it to dont save in appdata
but why does it now need admin rights?

**Comment by itsmattkc** [comment]
> but why does it now need admin rights?

Rebuilder actually explains this in the patch description:
![image](https://user-images.githubusercontent.com/34096995/102602353-88617700-4175-11eb-84ed-cfa4115b2d26.png)

The real question is why is the save patch failing on your end, it's one of the least intrusive patches we have.

Does your Windows username use any non-Latin characters by any chance? Also would you be able to provide your `LEGO1.DLL` from your LEGO Island installation?

**Comment by mjcox244** [comment]
[LEGO1.zip](https://github.com/itsmattkc/LEGOIslandRebuilder/files/5719152/LEGO1.zip)
and the name on my pc is mjcox
so there may be an issue with that LEGO1 file

**Comment by TonyAki** [comment]
Hi, I had the same error message, and it seems a few people are having similar issues. I piggybacked from [Neorocket64's post](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/22#issue-776378817). Note that I used the [Alternative Installer](https://github.com/le717/Island-Alternate-Installer) rather than doing it manually. Here's what I did, hope it helps:

1. Delete the LEGOIslandRebuilder folder within "AppData\Local\Temp"
2. Navigate to "Program Files(x86)\LEGO Island"
3. Right-click on CONFIG.EXE and open Properties
4. In the compatibility tab, check the "Run this program in compatibility mode for:" box and set the drop-down to "Windows XP (Service Pack 2)"
5. Run CONFIG.EXE, click Advanced, set it as "MMX Emulation", and uncheck the "Flip Video Memory Pages" box. Click OK to exit the configure window.
6. Now run LEGO Island Rebuilder (make sure it's in the "Program Files(x86)\LEGO Island" directory). You might have to do this one in compatibility mode as well.

**Comment by itsmattkc** [comment]
@mjcox244 Sorry about the lack of activity here. Could you send screenshots of the following registry keys:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mindscape\LEGO Island

Computer\HKEY_CURRENT_USER\SOFTWARE\Mindscape\LEGO Island

**Comment by itsmattkc** [comment]
I recommend retrying the new C++ version of Rebuilder. Closing due to age, if this remains an issue with the latest version, please create a new issue.
