### ISSUE TITLE
Erorr: "Lego Island failed to start"

### ISSUE THREAD

**Issue by Serutaef** [itsmattkc/LEGOIslandRebuilder#23]
Hello,

i am really glad there i someone trying to optimize this game for modern hardware.
I just tried to use the Lego Island Rebuilder after fiddling around with the german installation of the game.
While it runs with the usual issues without the Reubuilder, it gives me a black screen and the following error message when using the Rebuilder.exe:

![image](https://user-images.githubusercontent.com/38477337/103371175-1a9b4080-4acf-11eb-9ae3-10b7dcc0712e.png)

(it translates to: ""Lego Island" failed to start. Please close all applications and try again.")

Here is what I did:

- copied the files from the cd-rom to C:\Users\\[username]\Downloads
- installed game via INSTALL.exe
- opened folder C:\Program Files (x86)\LEGO Insel
- copied the file "d3drm.dll" from disc to installation folder
- activated checkmarks for "Compatibility mode" and set it to "Windows XP Service Pack 3" for the following files:
  - Config.exe
  - ISLE.exe
  - LEGOIsle.exe
  - Msrun.exe
- ran Config.exe and set following setttings:

![image](https://user-images.githubusercontent.com/38477337/103371315-6fd75200-4acf-11eb-99fe-b334b0c3605b.png)

- checked that game starts via click on ISLE.exe (it did/does)
- downloaded Rebuilder.exe and placed in C:\Program Files (x86)\LEGO Insel
- ran Rebuilder.exe and clicked on "Run" without changing any settings

Thats when the screen goes black and the error message appears.

What I already tried:
- i tried the alternate installer -> didn't help
- i checked the folder paths in registry -> they are correct
- i switched rendering modes -> didn't help

Other considerations:
- i am only using latin characters for my windows usernames
- i am not using dgvoodoo2

Greetings and thanks in advance!

**Comment by itsmattkc** [comment]
Does it work if you disable the "Re-direct saves to %APPDATA%" patch?

**Comment by Serutaef** [comment]
Sorry, I forgot to mention that I tried that option too. It does not work either.

**Comment by itsmattkc** [comment]
Can you send your LEGO1.DLL?

**Comment by Serutaef** [comment]
[LEGO1.zip](https://github.com/itsmattkc/LEGOIslandRebuilder/files/5755738/LEGO1.zip)
 here you go

**Comment by TonyAki** [comment]
Hi, I had the same error message, and it seems a few people are having similar issues. I piggybacked from [Neorocket64's post](https://github.com/itsmattkc/LEGOIslandRebuilder/issues/22#issue-776378817). Note that I used the [Alternative Installer](https://github.com/le717/Island-Alternate-Installer) rather than doing it manually. Here's what I did, hope it helps:

1. Delete the LEGOIslandRebuilder folder within "AppData\Local\Temp"
2. Navigate to "Program Files(x86)\LEGO Island"
3. Right-click on CONFIG.EXE and open Properties
4. In the compatibility tab, check the "Run this program in compatibility mode for:" box and set the drop-down to "Windows XP (Service Pack 2)"
5. Run CONFIG.EXE, click Advanced, set it as "MMX Emulation", and uncheck the "Flip Video Memory Pages" box. Click OK to exit the configure window.
6. Now run LEGO Island Rebuilder (make sure it's in the "Program Files(x86)\LEGO Island" directory). You might have to do this one in compatibility mode as well.

**Comment by Serutaef** [comment]
Hi TonyAki, thanks for the response. I followed your instructions but it didn't help. The same message still shows up.

**Comment by itsmattkc** [comment]
@Serutaef Sorry about the lack of activity here. Could you send screenshots of the following registry keys:

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mindscape\LEGO Island`

`Computer\HKEY_CURRENT_USER\SOFTWARE\Mindscape\LEGO Island`

**Comment by Icey67** [comment]
Hello Matt,
I may not be @Serutaef but i'm having the same issue with the same LEGO Island Game (which is also German)
May i be of help with that?
![Screenshot (7)](https://user-images.githubusercontent.com/60461186/144580792-ad8a295b-ae35-4db8-9969-0113ef21b31c.png)
![Screenshot (8)](https://user-images.githubusercontent.com/60461186/144580804-1db6557c-73fc-4844-838e-6e71ff34d965.png)

**Comment by itsmattkc** [comment]
@Icey67 It looks like you haven't run CONFIG.EXE (aka "To Configure LEGO Island") yet. Try running it (using "Windows 95" compatibility for the best results) and set it to the following:

![image](https://user-images.githubusercontent.com/34096995/144582070-cda47dfc-2d72-4584-96fd-1099a2fc2a01.png)

**Comment by Serutaef** [comment]
Hello Matt,

I am really sorry for not responding. Had some stuff to do and totally forgot about this.

@Icey67 - thanks for sharing. The registry keys were the same for me and today I figured out why:
If you are not logged in as admin on your computer, the CONFIG.EXE cannot write to the registry.
Therefore, start config.exe as admin.

Does your Rebuilder.exe need administrator privileges?

**Comment by Icey67** [comment]
Hello you two,
I tried trying out all of your recommendations and here are the results:
Yeah after setting that to RGB Emulation just made Lego Island be a low res black screen and with dgVoodoo the Audio works but yeah still black screen (resolution was 1920x1080 with dgVoodoo)

**Comment by Serutaef** [comment]
@Icey67 I don't use dgVoodoo, but my game will also crash when setting the "Direct 3D-Device" to "Direct3D HAL" in combination with Rebuilder.exe. If I choose "RGB Emulation" or "MMX Emulation" it works fine (no anti-aliasing though).

**Comment by itsmattkc** [comment]
@Serutaef Glad to hear this is fixed for you. In my experience, often even running as administrator doesn't work properly, which is why I usually recommend "Windows 95" compatibility (I'm surprised I didn't recommend that earlier in this issue). We actually have a new version of Rebuilder almost ready that replicates this functionality, meaning people won't have to deal with the clunkiness of CONFIG.EXE or having to run anything as administrator.

@Icey67 If you're using dgVoodoo, you should set it to "Direct3D HAL". On vanilla setups, "HAL" is extremely buggy so I don't tend to recommend it, but with dgVoodoo it's the one you should use.

**Comment by Malanao** [comment]
@itsmattkc I've tried doing everything in this thread, but I always get a black screen, the Audio works fine, i'm also using dgVoodoo like Icey, but I don't know what i'm doing wrong. Currently, the compatibility is set to Windows 95 for CONFIG.EXE, ISLE.EXE, LEGOisle.exe and Msrun.exe.

**Comment by Malanao** [comment]
Alright, so I disabled all the compatibility modes except for CONFIG.EXE which was set to Windows 95. In the Rebuilder I set the emulation to DirectHAL 3D and set Flip Video Memory Pages to True, and after that it worked flawlessly. Thanks Matt,
Love your vids btw, keep it up 👍

**Comment by itsmattkc** [comment]
Latest commit will correctly set compat flags based on the host OS version. Since this thread is old, pertains to a version of Rebuilder before it replaced CONFIG.EXE's functionality, and appears to have derailed from the OP, I'm going to close this for now. Anyone experiencing this issue should create a new thread.

**Comment by thisIsAnUnusedAccount** [comment]
Alright try putting d3drm.dll in the Program Files (x86) > LEGO Island and in the system32 folder. for me it worked
I got the dll from
https://www.dll-files.com/download/57ecb51c1682d12770ccd9b716dc4b6c/d3drm.dll.html?c=cENEczA4QlY4OVJyb1dDMVl2QnRQZz09
