### ISSUE TITLE
Generate Modified Lego Island .EXE file

### ISSUE THREAD

**Issue by m-orsh** [itsmattkc/LEGOIslandRebuilder#26]
Would be nice to be able to take the original .EXE file, pass it through the rebuilder, and generate a modified one. This way users could run the modified version of Lego Island's exe via something like Steam. Since having to go through the rebuilder first will prevent steam's hook from coming into play.

I imagine the rebuilder is essentially already doing this without actually generating the .exe file, so this would be nice to have as a separate feature and shouldn't be all that complicated.

**Comment by Ramen2X** [comment]
Rebuilder does this every time you click Run. You can access the modified game files at `%temp%\LEGOIslandRebuilder`. They stay there until they are re-patched the next time you click Run. Keep in mind that LEGO1.DLL is the file that contains most of the important patches as it contains the actual game code.

**Comment by m-orsh** [comment]
Thanks! I tried copying the temp folder elsewhere and running ISLE.EXE. It seems to be having issues visually though:
![image](https://user-images.githubusercontent.com/7002881/111854198-6bfbe480-88f4-11eb-94db-ee264f08e851.png)
This doesn't happen when I run normally via the rebuilder.

**Comment by Ramen2X** [comment]
This is because you copied the folder to a different location and ran the game from there. For windowed mode to work, ISLE.EXE needs to run in 16-bit color mode. Rebuilder sets a registry key to do this, however, as the location of ISLE.EXE moved, the registry key is no longer pointing to the correct location of ISLE.EXE. To correct this, you can go to Properties on ISLE.EXE and set it to run in 16-bit color mode.

**Comment by m-orsh** [comment]
That was it. It works as expected. No steam overlay but this is already nice as it can be launched from steam.
