### ISSUE TITLE
Lego Island opens but crashes in the information center after opening the game

### ISSUE THREAD

**Issue by KobyKB44** [itsmattkc/LEGOIslandRebuilder#28]
Hello I am new to lego island and I have tried playing it on windows xp before and the same thing happens on windows 10 I am using my macbook pro 2019 which has enough to run a VM because I can play other old games. The error I am facing is that lego island keeps crashing at one point and this point is when I try to leave the information center I don't know why this happens but the game keeps beeping and glitching out with the green and red bricks I will link a video to show what is happening and I still can't find any fixes to this, I have tried installing windows 98 but I can't get drivers onto it and I can't get a web browser that supports HTTPS, I have tried updating the USB drivers in the 98 driver panel but nothing works so I can't get my Firefox browser on the 98 VM or the drivers, kernelex or Lego Island if anyone has a fix for these 2 problems I am facing please leave a comment

The Lego Island Error Video:
https://www.youtube.com/watch?v=_y6Llr6eF7k skip to 2:20 in the video that is where the error starts

**Comment by mrpenguinb** [comment]
What version is your d3drm.dll? Also what have you got selected in LEGO Island's CONFIG.EXE, RGB Emulation or Direct3D HAL?
If you have Direct3D HAL selected, make sure you've installed dgVoodoo2.

I was able to successfully recreate the error by using RGB Emulation with dgVoodoo2 uninstalled. To fix it, install dgVoodoo2 and set the game to use Direct3D HAL instead of RGB Emulation or any of the options like Ramp or MMX.

**Comment by itsmattkc** [comment]
I recommend retrying with the latest commit. I will close this for now but feel free to reply if you're still experiencing this.
