### ISSUE TITLE
Use of Password Hash With Insufficient Computational Effort

### ISSUE THREAD

**Issue by Abelkrijgtalles** [itsmattkc/LEGOIslandRebuilder#37]
(BETA Suggestion) The SHA1 hash (used by global::System.Security.Cryptography.SHA1Managed) is insecure. Consider changing it to a secure hash algorithm.
Rebuilder/Rebuilder.cs Line 622:
`using (SHA1Managed sha1 = new `**SHA1Managed**`())`
**Details**
Sensitive information should never be stored in plain text, since this makes it very easy for unauthorized users, whether malicious insiders or outside attackers, to access. Hashing methods are used to make stored passwords and other sensitive data unreadable to users. For example, when a password is defined for the first time, it is hashed and then stored. The next time that user attempts to log on, the password they enter is hashed following the same procedure and compared with the stored value. In this way, the original password never needs to be stored in the system.

Hashing is a one-way scheme, meaning a hashed password cannot be reverse engineered. However, if an outdated or custom programmed hashing scheme is used, it becomes simple for an attacker with powerful modern computing power to gain access to the hashes used. This opens up access to all stored password information, leading to breached security. Therefore, it is essential for developers to understand modern, secure password hashing techniques.

**Comment by itsmattkc** [comment]
Thanks, but I can tell you're posting this to several repos (perhaps with a bot/script) without seeing how it's used, or else you'd know that Rebuilder does not use SHA-1 for passwords, and in fact doesn't utilize passwords at all.

SHA-1 is used for file verification here, which is a perfectly valid usage of it since there are virtually no security requirements/implications. In fact, the speed of computing it is its very strength in this scenario. Even MD5 is still used commonly for file verification.

Your post is clearly well-intentioned and an important message for developers. I appreciate that, but it has no relevance here.
