### ISSUE TITLE
Ordinal 6644 error when trying to start Rebuilder while it's in the LEGO Island Folder

### ISSUE THREAD

**Issue by CrazySeanDX** [itsmattkc/LEGOIslandRebuilder#41]
I've been trying everything I could think of, from uninstalling and reinstalling to removing the files from the last program modifying it in dgVooDoo, and even redownloaded it, but it keeps giving this same issue where the "ordinal 6644 could not be located in the dynamic link library" of the location it's in.

Please help me figure this out!!!!!

**Comment by itsmattkc** [comment]
There's a note on the README page about this:

> Note: Due to conflicting versions of MFC, Rebuilder will currently not function if placed in the same directory as LEGO Island.

Effectively, the version of `MFC42.DLL` that ships with LEGO Island is too old for Rebuilder, and for some reason Microsoft never changed the names of these DLLs despite being a significantly newer version. When they're in the same folder, Rebuilder picks up that old version rather than the newer version that comes on your system.

If you would really like Rebuilder in LEGO Island's folder, delete `MFC42.DLL` from it. That will allow Rebuilder to run with the system's `MFC42.DLL` (which should also be backwards compatible for LEGO Island).
