### ISSUE TITLE
Issues with the german version

### ISSUE THREAD

**Issue by TheWinHelper** [itsmattkc/LEGOIslandRebuilder#9]
Trying to run the Rebuilder with the German Release justs crashes the game imediatly after clicking run. The main game Window is shortly visible, but dirtectly exits again, without any message what so ever. The game version (lego1.dll) reads 1.1.0.0 . The game is running on a windows 10 based machine, running the 2004 build of Windows 10 and the game is running in compatible mode, with the dgvoodo setup running.
I would really appricte if you could take a look into it, as this is one of my only childhood games, that I still love to play today

**Comment by itsmattkc** [comment]
I assume you received the following message box:

![image](https://user-images.githubusercontent.com/34096995/77239675-a1aeb480-6c31-11ea-9ce1-2509e0fe5474.png)

This is a known issue, since a lot of the translations have recompiled the main files so the patch offsets have shifted around. At some point these other languages will be written in.

**Comment by itsmattkc** [comment]
Added support for the German release in 4e554ffc9f0885923814625fd29590aae5907444
