### ISSUE TITLE
bigger window size / hd option?

### ISSUE THREAD

**Issue by fishcelery4894** [itsmattkc/LEGOIslandRebuilder#93]
can we get this perhaps
idk how to use vgvoodoo and it just breaks the game

**Comment by Ramen2X** [comment]
This functionality exists as an experimental option in the .NET build, but please be aware that it was never completed due to complications with modifying the 2D hitboxes logic, so it will feel awkward to control.

My best suggestion for a playable experience in HD is to wait for the LEGO Island decompilation to complete. We are extremely close to implementing all functions, and our next objective will switch to producing a modern build of the game afterwards.
